[project]
name = "fhba"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "needham-michael", email = "153653339+needham-michael@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "earthaccess>=0.16.0",
    "geopandas>=1.1.2",
    "geotiff>=0.2.10",
    "geoviews>=1.15.1",
    "h5netcdf>=1.8.1",
    "holoviews>=1.22.1",
    "netcdf4>=1.7.4",
    "numpy>=2.4.2",
    "panel>=1.8.7",
    "pycoast>=1.8.0",
    "pydecorate",
    "pyspectral>=0.14.1",
    "rasterio>=1.5.0",
    "satpy>=0.59.0",
    "scipy>=1.17.0",
    "tqdm>=4.67.3",
    "zarr>=2.12.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipywidgets>=8.1.8",
    "jupyterlab>=4.5.3",
    "ruff>=0.15.0",
]
